# Site settings
title: Handbook of Quantum Machine Learning
email: scinawa@luongo.pro
description: >
  The online resource for doing quantum machine learning.
baseurl: ""
url: "https://luongo.pro/qml"
twitter_username: scinawa
github_username:  scinawa

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - vendor/bundle
